### ISSUE TITLE
로그인 기능구현

### ISSUE THREAD

**Issue by yujin4sth00** [ssg-240304-java2/wms-3355ABC#1]
###  🔥 로그인 기능 구현
가맹점과 관리자 ID로 나뉘어 로그인. 관리자 설정에 맞도록 로그인 후 계정에 맞는 메인화면 연결

## ✔️TODO
- [x] 관리자 ID 로그인
- [x] 가맹점 ID 로그인
- [x] 각 ID에 맞게 메뉴 보여주기
- [x] 팀원들 기능 맞게 넣어 오류없이 실행되는 지 확인
## [최종 결과]
- [x]  최종 MERGE 완료
**- BRANCH NAME : feature/users**

**Comment by yujin4sth00** [comment]
- 로그인을 했을 때 테이블에 있는 값이 아닌  값들이 들어오면 null값에 의해 에러나는 것 수정 완료
- 로그인 메뉴 돌리면서 사소한 오류 수정 중
- 팀원들이 구현한 메소드 LoginView에 다 작성될 때까지 기다리는 중입니다.
