### ISSUE TITLE
주문서작성

### ISSUE THREAD

**Issue by yj0318** [ssg-240304-java2/wms-3355ABC#6]
### 🔥 주문서 작성
[본사 로그인시]
본사에 필요한 상품을 주문하는 기능을 구현

## ✔️ TODO
- [x] 가맹점에서 주문서 작성하기
- [x] 작성한 주문서를 ORDER_PRODUCT와 ORDER_DETAIL 에 INSERT하기

#### 조건부 제작 @Gyunorld 
- [x] 입력한 값을 기준으로 재고 조회
- [x] 현재 재고 상황에 주문 가능한 조건인지 확인

#### View 제작 @DISNOTACAT 
- [x] 상품명 검색, 옵션 입력 및 검증
- [x] 상품 반복 추가 기능
- [x] 유저 정보 같이 INSERT 하기

## [최종 결과]
- [x]  최종 MERGE 완료
**- BRANCH NAME : feature/salesmanager**
